name: Anita Ho
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3657177046407014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1115'
    - '#eff1f0'
    - '#9c3b10'
    - '#abbfb3'
    - '#1186bb'
  brandStrength: 0.75
  lightness: 0.34856724366545677
  saturation: 0.3995369777549058
  rhythmicContrast: 0.820946095045656
purpose: []
